from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name='HomePage'),
    path('dashboard/', views.dashboard, name='DashboardPage'),
    path('signup/', views.signupPage, name='SignUpPage'),
    path('login/', views.loginPage, name='LoginPage'),
    path('contact/', views.contactPage, name='ContactPage'),
    path('about/', views.aboutpage, name='AboutPage'),
    path('process-signup', views.ProcessSignUp, name='handle-sign-up-form'),
    path('process-login', views.ProcessLogin, name='handle-login-form'),
    path('logout/', views.logoutPage, name='LogoutPage'),
    path('transfer/', views.transferPage, name='TransferPage'),
    path('deposit/', views.depositPage, name='DepositPage'),
    path('paystack/init/', views.initialize_paystack_deposit, name='initialize_paystack_deposit'),
    path('callback/', views.paystack_callback, name='paystack_callback'),
    path('process-transfer', views.processTransfer, name='handle-transfer'),
    path('process-deposit', views.processDeposit, name='handle-deposit'),
    path('process-withdrawal', views.processWithdrawal, name='handle-withdrawal'),
    path('profile/', views.profilePage, name='ProfilePage'),
    path('profile/update-info', views.updateInfo, name='UpdateInfo'),
    path('profile/update-password', views.updatePassword, name='UpdatePassword'),
    path('profile/update-pin', views.updatePin, name='UpdatePin'),
    path('history/', views.historyPage, name='HistoryPage'),
    path('verify-account/', views.verifyAccount, name='VerifyAccount'),
    path('withdraw/', views.withdrawPage, name='WithdrawPage'),
    path('process-withdraw', views.processWithdraw, name='handle-withdraw'),
    path('bills/', views.billsPage, name='BillsPage'),
    path('process-bill', views.processBill, name='handle-bill'),
    path('airtime/', views.airtimePage, name='AirtimePage'),
    path('process-airtime', views.processAirtime, name='handle-airtime'),
    path('callback/', views.paystack_callback, name='PaystackCallback'),
    path('deposit/', views.depositPage, name='DepositPage'),
    path('initialize-deposit/', views.initialize_paystack_deposit, name='InitializeDeposit'),
]