# Generated by Django 6.0.5 on 2026-05-25 13:03

import FundUsApp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvn', models.CharField(max_length=11)),
                ('dob', models.DateField()),
                ('phonenumber', models.CharField(max_length=14)),
                ('accountBalance', models.DecimalField(decimal_places=3, default=0.0, max_digits=9)),
                ('accountNumber', models.CharField(default=FundUsApp.models.generateAccountNumber, max_length=10)),
                ('pin', models.CharField(blank=True, max_length=4)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('U', 'UNSPECIFIED')], default='U', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
