# Generated by Django 6.0.5 on 2026-06-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundUsApp', '0002_alter_customer_user_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bvn',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phonenumber',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
    ]
