# Generated by Django 6.0.5 on 2026-06-10 12:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundUsApp', '0003_alter_customer_bvn_alter_customer_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='accountBalance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
