# Generated by Django 6.0.5 on 2026-06-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundUsApp', '0004_alter_customer_accountbalance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
